version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7
    container_name: card-parser-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=card_parser
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/card_parser --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: card-parser-backend
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - /app/__pycache__
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DB_NAME=card_parser
      - ENVIRONMENT=production
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: card-parser-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend

volumes:
  mongodb_data:
    driver: local
